name: Reuse .NET Build Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build:
    runs-on: ubuntu-latest

    steps:
      - name: Build DotNet App
        uses: ./.github/actions/build-dotnet
        with:
          project-path: 'DotNet'
